trigger:
- main

variables:
- group: python-cli-example-lib

jobs:
- job: CheckProjectVersionAndPublish
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - script: |
      latest_version=$(curl -s https://pypi.org/pypi/python-phrase/json | jq -r .info.version)
      echo "Latest version on PyPI: $latest_version"

      local_version=$(grep -oP "(?<=version=')[^']+" setup.py)
      echo "Local version in setup.py: $local_version"

      if [ "$latest_version" != "$local_version" ]; then
        echo "Versions are different. Uploading to PyPI."
        pip3 install pyinstaller
        pip3 install twine
        python3 setup.py sdist
        python3 -m twine upload dist/* --username __token__ --password $(pip_api_key)
      else
        echo "Versions are the same. Skipping PyPI upload."
      fi

- job: PublishPackageToChocolatey
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      pip install pyinstaller
    displayName: 'Install PyInstaller'

  - script: |
      pyinstaller $(spec_file_name).spec
      choco pack
      choco push $(nupkg_file_name).$(choco_cli_version).nupkg -s https://chocolatey.org/ --api-key $(choco_api_key)
    displayName: 'Publish Package to Chocolatey'
